#!/bin/bash
#NOTE: DO NOT EDIT THIS FILE-- MAY RESULT IN INCOMPLETE SUBMISSIONS
set -euo pipefail

pushd submission

CODE=(
	"xcs231n/classifiers/k_nearest_neighbor.py"
	"xcs231n/classifiers/linear_classifier.py"
	"xcs231n/classifiers/softmax.py"
	"xcs231n/classifiers/fc_net.py"
	"xcs231n/optim.py"
	"xcs231n/solver.py"
	"xcs231n/layers.py"
)

# these notebooks should ideally
# be in order of questions so
# that the generated pdf is
# in order of questions
NOTEBOOKS=(
	"knn.ipynb"
	"softmax.ipynb"
	"two_layer_net.ipynb"
	"features.ipynb"
	"FullyConnectedNets.ipynb"
)

FILES=( "${CODE[@]}" "${NOTEBOOKS[@]}" )

LOCAL_DIR=`pwd`
ASSIGNMENT_NO=1
ZIP_FILENAME="../a1.zip"

C_R="\033[31m"
C_G="\033[32m"
C_BLD="\033[1m"
C_E="\033[0m"

for FILE in "${FILES[@]}"
do
	if [ ! -f ${FILE} ]; then
		echo -e "${C_R}Required file ${FILE} not found, Exiting.${C_E}"
		exit 0
	fi
done

echo -e "### Zipping file ###"
rm -f ${ZIP_FILENAME}
zip -q "${ZIP_FILENAME}" -r ${NOTEBOOKS[@]} $(find . -name "*.py") "xcs231n/saved" -x "makepdf.py"

FULL_ZIP_PATH=$(realpath ${ZIP_FILENAME})
BASE_NAME=$(basename ${ZIP_FILENAME})
echo -e "### Done! Please submit ${BASE_NAME} to Gradescope. ###"
echo -e "### Full path: ${FULL_ZIP_PATH} ###"

popd